from setuptools import setup, find_packages

setup(
    name="alarmdecoder-webapp",
    version="0.8.6",  # update as appropriate for new release
    url="https://github.com/nutechsoftware/alarmdecoder-webapp",
    description="Web interface for the AlarmDecoder home security devices",
    author="Nu Tech Software Solutions, Inc.",
    author_email="ad2usb@support.nutech.com",
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        "Flask",
        "Flask-SQLAlchemy",
        "Flask-WTF",
        "Flask-Babel",
        "Flask-Login",
        "Flask-OpenID",
        "Flask-Mail",
        "Flask-Testing",
        "alarmdecoder>=0.9",
        "pyopenssl",
        "gevent-socketio",
        "jsonpickle",
        "sleekxmpp",
        "psutil>=2.0.0",
        "sh",
        "alembic",
        "netifaces",
        # Note: Removed 'Flask-Script' and 'Flask-Cache' if no longer used in updated app
    ],
    python_requires=">=3.6",
    test_suite="tests",
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Environment :: Web Environment",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
        "Topic :: Software Development :: Libraries",
        "Topic :: Communications",
        "Topic :: Home Automation",
        "Topic :: Security",
    ],
)
